project13/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific
urlpatterns = [
    path('admin/', admin.site.urls),
    path('generic/',generic,name='generic'),
    path('mapping/',mapping,name='mapping'),

    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path
app_name = 'specific'
urlpatterns = [
    path('specific/',specific,name='specific'),
    path('mappingspe/',mappingspe,name='mappingspe'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def generic(request):
    return render(request,'generic.html')

def mapping(request):
    return render(request,'mapping.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def specific(request):
    return render(request,'specific.html')

def mappingspe(request):
    return render(request,'mappingspe.html')

templates/generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hii..........Hello(Generic)</h1>
    <a href="{% url 'mapping' %}"><h1>Mapping</h1></a>
    <a href="{% url 'specific:mappingspe' %}"><h1>mappingspe</h1></a>
    <a href="{% url 'specific:specific' %}"><h1>Specific</h1></a>
    </center>
</body>
</html>

templates/mapping.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Heyyyy.......r u there(Mapping)</h1>
    <a href="{% url 'generic' %}"><h1>Generic</h1></a>
    <a href="{% url 'specific:mappingspe' %}"><h1>Mappingspe</h1></a>
    <a href="{% url 'specific:specific' %}"><h1>Specific</h1></a>
</center>
</body>
</html>

templates/mappingspe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>Hai......Hai(mappingspe)</h1>
    <a href="{% url 'generic' %}"><h1>Generic</h1></a>
    <a href="{% url 'mapping' %}"><h1>Mapping</h1></a>
    <a href="{% url 'specific:specific' %}"><h1>Specific</h1></a>
</center>
</body>
</html>

templates/specific.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center>
    <h1>
        Ur good Looking.........(Specific)
    </h1>
    <a href="{% url 'generic' %}"><h1>Generic</h1></a>
    <a href="{% url 'mapping' %}"><h1>Mapping</h1></a>
    <a href="{% url 'specific:mappingspe' %}"><h1>mappingspe</h1></a>
   </center> 
</body>
</html>